//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PasswordS
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuthorizeInform
    {
        public int Id { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public string Link { get; set; }
        public string UserAuthorize_User { get; set; }
        public string Other { get; set; }
    
        public virtual UserAuthorize UserAuthorize { get; set; }
    }
}
